model_type: caformer_s18
depths: [3, 3, 9, 3]
dims: [64, 128, 320, 512]
use_mlp_head: true 
mlp_bias: false
token_mixer: ca
block_norm: layer_norm
main_norm: layer_norm
downsample_norm: layer_norm
layer_scale_init_values: null
res_scale_init_values: [null, null, 1.0, 1.0]
mlp_act: star_relu

