model_type: poolformerv2_m36
depths: [6, 6, 18, 6]
dims: [96, 192, 384, 768]
use_mlp_head: false 
mlp_bias: false
token_mixer: pooling
block_norm: group_norm_1grp
main_norm: layer_norm
downsample_norm: layer_norm
layer_scale_init_values: null
res_scale_init_values: [null, null, 1.0, 1.0]
mlp_act: star_relu

