model_type: randformer_s24
depths: [4, 4, 12, 4]
dims: [64, 128, 320, 512]
use_mlp_head: false 
mlp_bias: false
token_mixer: random_mixer
block_norm: layer_norm
main_norm: layer_norm
downsample_norm: layer_norm
layer_scale_init_values: null
res_scale_init_values: [null, null, 1.0, 1.0]
mlp_act: star_relu

